# -*- coding: utf-8 -*-
"""all_user_deatils_11_28_2023_submission

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u1KFl7HlgsHxFtDlvxHzXmvxYmaaA8XF
"""

import pandas as pd

# Assuming "Autoware Contributors.xlsx" is in the same directory as your script
excel_file_path = "Autoware Contributors.xlsx"

# Read Excel file into a DataFrame
df_excel = pd.read_excel(excel_file_path)

# Display basic information about the DataFrame
print("Excel File Information:")
print(df_excel.info())

# Display the first few rows of the DataFrame
print("\nFirst Few Rows:")
print(df_excel.head())

import pandas as pd

# Assuming "user_details_all.csv" is in the same directory as your script
csv_file_path = "user_details_all.csv"

# Read CSV file into a DataFrame
df_csv = pd.read_csv(csv_file_path)

# Display basic information about the DataFrame
print("CSV File Information:")
print(df_csv.info())

# Display the first few rows of the DataFrame
print("\nFirst Few Rows:")
print(df_csv.head())

# Concatenate DataFrames vertically
concatenated_df = pd.concat([df_excel, df_csv], ignore_index=True)

# Deduplicate based on 'pull_request_user_id'
deduplicated_df = concatenated_df.drop_duplicates(subset='user_id', keep='first')

# Save the deduplicated DataFrame to a new CSV file
deduplicated_df.to_csv('ur_all.csv', index=False)

# Display basic information about the deduplicated DataFrame
print("Deduplicated DataFrame info:")
print(deduplicated_df.info())