# -*- coding: utf-8 -*-
"""issues_user_details_11_29_2023_start

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18x5HYzVYwYNlCK6GaIoDeDNn2jku_0n-
"""

import pandas as pd
import requests
import matplotlib.pyplot as plt
import seaborn as sns

# List of years for which you have datasets (update as needed)
years = range(2015, 2024)

# Initialize an empty list to store DataFrames
issues_dfs = []

# Read and append data for each year
for year in years:
    # Replace 'your_file_path' with the actual path to your CSV file
    csv_file_path = f'issues_{year}.csv'

    # Read the CSV file into a DataFrame
    issues_df = pd.read_csv(csv_file_path)

    # Append the DataFrame to the list
    issues_dfs.append(issues_df)

# Concatenate all DataFrames in the list into a single DataFrame
combined_issues_df = pd.concat(issues_dfs, ignore_index=True)

# Display basic information about the combined DataFrame
print("Basic Information about the Combined DataFrame:")
print(combined_issues_df.info())

# GitHub GraphQL API endpoint
graphql_url = "https://api.github.com/graphql"

# Replace 'YOUR_PERSONAL_ACCESS_TOKEN' with your GitHub personal access token
access_token = "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"

headers = {
    "Authorization": f"Bearer {access_token}"
}

# Function to fetch user details from GitHub GraphQL API
def fetch_user_details(username):
    query = """
    query {
        user(login: "%s") {
            login
            email
            location
            url
            followers {
                totalCount
            }
            following {
                totalCount
            }
            company  # Modified to use 'company' instead of 'organization'
        }
    }
    """ % username

    response = requests.post(graphql_url, json={"query": query}, headers=headers)

    if response.status_code == 200:
        user_data = response.json().get("data", {}).get("user", {})
        return user_data
    else:
        return None

# Create a list to store user details
user_details_list = []

# Iterate over each unique author in the combined issues DataFrame
for author in combined_issues_df['issues_comment_author'].unique():
    user_data = fetch_user_details(author)

    if user_data:
        user_details_list.append({
            'issues_comment_author': author,
            'company': user_data.get('company'),  # Use 'company' instead of 'organization'
            'email': user_data.get('email'),
            'location': user_data.get('location'),
            'social_media_link': user_data.get('url'),
            'followers': user_data.get('followers', {}).get('totalCount'),
            'followings': user_data.get('following', {}).get('totalCount')
        })

# Create a new DataFrame from the list
user_details_df = pd.concat([pd.DataFrame([user_details]) for user_details in user_details_list], ignore_index=True)

# Save the extended user details DataFrame to a new CSV file
user_details_csv_file = 'user_details_combined.csv'
user_details_df.to_csv(user_details_csv_file, index=False)

print(f"\nUser details saved to {user_details_csv_file}")

# Read the CSV file into a DataFrame
user_details_df = pd.read_csv(user_details_csv_file)

# 1. General Overview
print("1. General Overview:")
print(user_details_df.head())
print(user_details_df.info())

# 2. Statistical Summary
print("\n2. Statistical Summary:")
print(user_details_df.describe())

# 3. Number of Unique Values in Each Column
print("\n3. Number of Unique Values in Each Column:")
for column in user_details_df.columns:
    unique_values_count = user_details_df[column].nunique()
    print(f"{column}: {unique_values_count} unique values")

# 4. Count of Users with Company Information
users_with_company_info = user_details_df['company'].notnull().sum()
print(f"\n4. Count of Users with Company Information: {users_with_company_info} users")

# 5. Categorizing Users Based on Company Names
company_threshold = 5  # Example: consider companies with at least 5 occurrences
top_companies = user_details_df['company'].value_counts().head(company_threshold).index

user_details_df['company_category'] = user_details_df['company'].apply(
    lambda x: x if pd.notnull(x) and x in top_companies else 'Other'
)

# Display the count of users in each company category
print("\n5. Categorizing Users Based on Company Names:")
print(user_details_df['company_category'].value_counts())

# Plot the distribution of users in each company category
plt.figure(figsize=(10, 6))
sns.countplot(x='company_category', data=user_details_df)
plt.title('Distribution of Users Based on Company Categories')
plt.show()