# -*- coding: utf-8 -*-
"""PR_Combine_all.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/139KGhOuRP_qvy8J0qm-RrNsVc8sVmBwn
"""

import pandas as pd

# Load CSV files into DataFrames
user_details_PR_commiters_df = pd.read_csv('user_details_PR_commiters.csv')
user_details_PR_id_df = pd.read_csv('user_details_PR_id.csv')
user_details_comment_df = pd.read_csv('user_details_comment.csv')

# Display basic information about each DataFrame
print("user_details_PR_commiters_df info:")
print(user_details_PR_commiters_df.info())

print("\nuser_details_PR_id_df info:")
print(user_details_PR_id_df.info())

print("\nuser_details_comment_df info:")
print(user_details_comment_df.info())

# Concatenate DataFrames vertically
concatenated_df = pd.concat([user_details_PR_commiters_df, user_details_PR_id_df, user_details_comment_df], ignore_index=True)

# Deduplicate based on 'pull_request_user_id'
deduplicated_df = concatenated_df.drop_duplicates(subset='pull_request_user_id', keep='first')

# Save the deduplicated DataFrame to a new CSV file
deduplicated_df.to_csv('pr_user_details_all.csv', index=False)

# Display basic information about the deduplicated DataFrame
print("Deduplicated DataFrame info:")
print(deduplicated_df.info())